import type { Metadata } from "next";
import { ClerkProvider, auth } from "@clerk/nextjs";
import { useContext } from "react";
import { Inter } from "next/font/google";
import "./globals.css";
import styles from "./layout.module.css";
import { StoreProvider as Provider } from "./Components/Context/StoreProvider";
// import ContextProvider from "./Components/Context/ContextProvider";
import SideBar from "./Components/SideBar/SideBar";
import NextTopLoader from "nextjs-toploader";
const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  const { userId } = auth();
  return (
    <ClerkProvider>
      <html lang="en">
        <body className={inter.className}>
          <NextTopLoader
            height={2}
            color="#27AE60"
            easing="cubic-beizer(0.53, 0.21, 0,1)"
            showSpinner={false}
          />
          <Provider>
            <div className={styles.layOut}>
              {userId && <SideBar />}
              <div className="w-full"> {children}</div>
            </div>
          </Provider>
        </body>
      </html>
    </ClerkProvider>
  );
}
