import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import styles from "./layout.module.css";
import ContextProvider from "./Components/Context/contextProvider";
import SideBar from "./Components/SideBar/SideBar";
const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <ContextProvider>
          <div className={styles.layOut}>
            <SideBar />
            {children}
          </div>
        </ContextProvider>
      </body>
    </html>
  );
}
